version: "3.1"

language: en

pipeline:
  - name: WhitespaceTokenizer

  - name: RegexFeaturizer

  - name: LexicalSyntacticFeaturizer

  - name: CountVectorsFeaturizer

  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  - name: DIETClassifier
    epochs: 200
    constrain_similarities: true

policies:
  - name: MemoizationPolicy

  - name: RulePolicy

  - name: TEDPolicy
    max_history: 10
    epochs: 200

  - name: UnexpecTEDIntentPolicy
    epochs: 100

assistant_id: 20260713-180450-simple-kicker